In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
lin = nn.Linear(5,3)
data = torch.randn(2,5)
print(data)
print(lin(data))

tensor([[-1.1948,  0.0250, -0.7627,  1.3969, -0.3245],
        [ 0.2879,  1.0579,  0.9621,  0.3935,  1.1322]])
tensor([[ 0.1755, -0.3268, -0.5069],
        [-0.6602,  0.2260,  0.1089]], grad_fn=<AddmmBackward>)


In [3]:
data = torch.randn(2,2)
print(data)
print(F.relu(data))

tensor([[-0.5404, -2.2102],
        [ 2.1130, -0.0040]])
tensor([[0.0000, 0.0000],
        [2.1130, 0.0000]])


In [5]:
data = torch.randn(2,2)
print(data)
print(F.relu(data))

tensor([[ 1.3800, -1.3505],
        [ 0.3455,  0.5046]])
tensor([[1.3800, 0.0000],
        [0.3455, 0.5046]])


In [6]:
data = torch.randn(5)
print(data)
print(F.softmax(data,dim=0))
print(F.softmax(data,dim=0).sum()) # Sums to 1 because it is distribution

tensor([ 1.8213, -0.1814, -0.9515,  0.4057, -1.5164])
tensor([0.6776, 0.0915, 0.0423, 0.1645, 0.0241])
tensor(1.0000)


In [ ]:
data = [("me gusta comer en la cafeteria".split(), "SPANISH"),
        ("Give it to me".split(), "ENGLISH"),
        ("No creo que sea una buena idea".split(), "SPANISH"),
        ("No it is not a good idea to get lost at sea".split(), "ENGLISH")]

test_data = [("Yo creo que si".split(), "SPANISH"),
             ("it is lost on me".split(), "ENGLISH")]

word_to_idx = {}
for sent, _ in data + test+data:
    for word in sent:
        if word not in word_to_idx:
            word_to_idx[word] = len(word_to_idx)
print(word_to_idx)

Vocab_size = len(word_to_idx)
num_labels = 2

